Post
rust-community/underhanded.rs pull request #2
Opened 2016-12-14 11:20 UTC by ZhangHanDong

add Simplified Chinese translation

2016-12-14 16:20 UTC, erickt commented
This is amazing! Thank you so much! I can't help with the translation, but gets an r+ from me :)

2016-12-14 17:03 UTC, Manishearth commented
r? @KiChjang

2016-12-14 20:44 UTC, KiChjang requested changes
再次感谢您的贡献！请记得英文的版本还没完成好，所以中文版本也要随着更新。以下我留了几项备注：

2016-12-14 20:44 UTC, KiChjang commented on _posts/2016-12-08-underhanded-rust.zh_cn.md
> +Specific](https://github.com/ctjhoa/rust-learning#locale-links)开始。
Local Specific 不是文档的名称，在这儿的大概意思是“特定语言的资讯”。

2016-12-14 20:44 UTC, KiChjang commented on _posts/2016-12-08-underhanded-rust.zh_cn.md
> +Author #2
这个应该可以翻译成中文。

2016-12-14 20:44 UTC, KiChjang commented on _posts/2016-12-08-underhanded-rust.zh_cn.md
> +如果获奖者不希望提供用于寄送奖品的必要身份信息，则奖品会被捐赠给慈善机构。第一名之后的获奖者将会获得Rust-specific奖品（[比如贴纸、T恤](https://gist.github.com/brson/169768d19359fcac631c0bf7998acca8)）。
`具有Rust特色的奖品`好一些吗？

2016-12-14 20:44 UTC, KiChjang commented on _posts/2016-12-08-underhanded-rust.zh_cn.md
> +`AUTHORS` 文件应为您团队中每个成员包含以下内容。作者们将按照放置在此文件中的顺序列出，因此，可以由您来决定是否将他们按照最少贡献的顺序或仅按字母顺序排列。
笔画顺序排列也行吧？

2016-12-14 20:51 UTC, KiChjang commented
另外也想麻烦您更改`_include/footer.html`，把中文的超链接加上去。谢谢！

2016-12-15 06:05 UTC, ZhangHanDong commented on _posts/2016-12-08-underhanded-rust.zh_cn.md
> +`AUTHORS` 文件应为您团队中每个成员包含以下内容。作者们将按照放置在此文件中的顺序列出，因此，可以由您来决定是否将他们按照最少贡献的顺序或仅按字母顺序排列。
拼音顺序吧？ 中文应该很少按笔划顺序排列吧，还得数。

2016-12-15 06:39 UTC, erickt commented
Hello @ZhangHanDong and @KiChjang! I just merged some things in, so this has a conflict. Can you rebase? Also, if this is in an okay place, I'd like to merge it in so we can fix any broken links. We can make further changes in a future PR. Thanks! You all are wonderful.

2016-12-15 06:57 UTC, ZhangHanDong commented
@erickt ok.

2016-12-15 06:58 UTC, merged

2016-12-15 06:58 UTC, erickt commented
Thanks!